#!/bin/bash
###############################################################################
# AgentForge — One-Time Server Setup Script
# Run this ONCE on a fresh Ubuntu VPS (Contabo/Hetzner/DigitalOcean)
#
# Usage:
#   ssh root@YOUR_IP
#   curl -fsSL https://raw.githubusercontent.com/amtariksha/agentforge/main/scripts/setup-server.sh | bash
#
#   OR copy this file to the server and run:
#   chmod +x setup-server.sh && sudo ./setup-server.sh
#
# What this does:
#   1. Updates system packages
#   2. Creates 'agentforge' user
#   3. Installs Docker + Docker Compose
#   4. Installs Nginx + Certbot
#   5. Configures firewall (UFW)
#   6. Clones the repo
#   7. Generates secrets and creates .env
#   8. Builds and starts all services
#   9. Runs database migrations + seeds
#   10. Sets up Nginx reverse proxy
#
# After running, you need to:
#   - Point your domain DNS to this server's IP
#   - Run: sudo certbot --nginx -d api.yourdomain.com
#   - Update .env with your actual API keys (Anthropic, WhatsApp, etc.)
#   - Update Nginx config with your domain
###############################################################################

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[SETUP]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Must run as root
[[ $EUID -eq 0 ]] || err "Run this script as root: sudo ./setup-server.sh"

DEPLOY_USER="agentforge"
APP_DIR="/home/${DEPLOY_USER}/apps/agentforge"
REPO_URL="https://github.com/amtariksha/agentforge.git"

###############################################################################
# 1. System update
###############################################################################
log "Updating system packages..."
apt update && apt upgrade -y
apt install -y curl git ufw nginx certbot python3-certbot-nginx

###############################################################################
# 2. Create deploy user (if not exists)
###############################################################################
if id "${DEPLOY_USER}" &>/dev/null; then
    log "User '${DEPLOY_USER}' already exists"
else
    log "Creating user '${DEPLOY_USER}'..."
    adduser --disabled-password --gecos "" "${DEPLOY_USER}"
    usermod -aG sudo "${DEPLOY_USER}"
    # Allow sudo without password for deploy scripts
    echo "${DEPLOY_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${DEPLOY_USER}
fi

###############################################################################
# 3. Install Docker
###############################################################################
if command -v docker &>/dev/null; then
    log "Docker already installed: $(docker --version)"
else
    log "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
fi
usermod -aG docker "${DEPLOY_USER}"

# Ensure Docker starts on boot
systemctl enable docker
systemctl start docker

###############################################################################
# 4. Configure firewall
###############################################################################
log "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
# Port 3000 only on localhost (Nginx proxies)
ufw --force enable
log "Firewall configured: SSH + HTTP + HTTPS"

###############################################################################
# 5. Clone repo
###############################################################################
log "Cloning repository..."
sudo -u "${DEPLOY_USER}" mkdir -p "/home/${DEPLOY_USER}/apps"

if [[ -d "${APP_DIR}" ]]; then
    log "Repo already exists, pulling latest..."
    sudo -u "${DEPLOY_USER}" git -C "${APP_DIR}" pull origin main
else
    sudo -u "${DEPLOY_USER}" git clone "${REPO_URL}" "${APP_DIR}"
fi

###############################################################################
# 6. Generate secrets and create .env
###############################################################################
ENV_FILE="${APP_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
    warn ".env already exists — skipping generation. Edit manually if needed."
else
    log "Generating secrets and creating .env..."

    JWT_SECRET=$(openssl rand -hex 32)
    ENCRYPTION_KEY=$(openssl rand -hex 16)
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
    REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

    cat > "${ENV_FILE}" << ENVEOF
# ===== Generated by setup-server.sh on $(date -Iseconds) =====

# Database
POSTGRES_USER=agentforge
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=agentforge
DATABASE_URL=postgresql://agentforge:${POSTGRES_PASSWORD}@postgres:5432/agentforge

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# Server
PORT=3000
HOST=0.0.0.0
NODE_ENV=production

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=24h
JWT_REFRESH_EXPIRES_IN=7d

# Encryption (tenant credentials)
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Anthropic — REPLACE with your actual key
ANTHROPIC_API_KEY=sk-ant-REPLACE-ME

# OpenAI (for embeddings, optional)
OPENAI_API_KEY=

# Swarg Food WhatsApp — REPLACE with actual values
SWARG_WA_PHONE_ID=
SWARG_WA_WABA_ID=
SWARG_WA_ACCESS_TOKEN=
SWARG_WA_VERIFY_TOKEN=
SWARG_WA_APP_SECRET=

# Logging
LOG_LEVEL=info
ENVEOF

    chown "${DEPLOY_USER}:${DEPLOY_USER}" "${ENV_FILE}"
    chmod 600 "${ENV_FILE}"

    log "Generated .env with random secrets"
    warn "IMPORTANT: Edit ${ENV_FILE} to add your Anthropic API key and WhatsApp credentials"
fi

###############################################################################
# 7. Detect architecture: all-in-one vs separate DB server
###############################################################################
source "${ENV_FILE}"
COMPOSE_FILE="docker-compose.prod.yml"

# If DATABASE_URL points to a remote host (not postgres/localhost), use app-only compose
DB_HOST=$(echo "${DATABASE_URL:-}" | sed -n 's|.*@\([^:]*\):.*|\1|p')
if [[ -n "${DB_HOST}" && "${DB_HOST}" != "postgres" && "${DB_HOST}" != "localhost" && "${DB_HOST}" != "127.0.0.1" ]]; then
    COMPOSE_FILE="docker-compose.app.yml"
    log "Detected remote database at ${DB_HOST} — using app-only compose (no local Postgres)"
else
    log "Using all-in-one compose (app + Postgres + Redis on this server)"
fi

###############################################################################
# 8. Build and start services
###############################################################################
log "Building and starting Docker services (${COMPOSE_FILE})..."
cd "${APP_DIR}"
sudo -u "${DEPLOY_USER}" docker compose -f "${COMPOSE_FILE}" up -d --build

if [[ "${COMPOSE_FILE}" == "docker-compose.prod.yml" ]]; then
    # Wait for local Postgres
    log "Waiting for PostgreSQL to be ready..."
    for i in {1..30}; do
        if sudo -u "${DEPLOY_USER}" docker compose -f "${COMPOSE_FILE}" exec -T postgres pg_isready -U agentforge &>/dev/null; then
            log "PostgreSQL is ready"
            break
        fi
        sleep 2
    done
fi

# Wait for app to start
sleep 5

###############################################################################
# 9. Run migrations and seed
###############################################################################
# drizzle-kit push MUST run first — it creates every table from the TS schema.
# The drizzle/*.sql files only ALTER those tables (pgvector columns, indexes,
# RLS), so they fail with "relation does not exist" if applied before push.
log "Running database migrations (drizzle-kit push)..."
sudo -u "${DEPLOY_USER}" docker compose -f "${COMPOSE_FILE}" exec -T app npx drizzle-kit push 2>&1 || warn "Migration may need manual review"

if [[ "${COMPOSE_FILE}" == "docker-compose.prod.yml" ]]; then
    # Apply ALL raw SQL migrations in order (pgvector columns, indexes, RLS).
    # They are idempotent (IF NOT EXISTS / DROP POLICY IF EXISTS), so re-running
    # is safe. Applied after push so the target tables already exist.
    for sql in $(ls "${APP_DIR}"/drizzle/*.sql | sort); do
        log "Applying $(basename "${sql}")..."
        sudo -u "${DEPLOY_USER}" docker compose -f "${COMPOSE_FILE}" exec -T postgres \
            psql -U agentforge -d agentforge < "${sql}" 2>&1 || warn "$(basename "${sql}") may need manual review"
    done
else
    log "Skipping RLS SQL — run drizzle/*.sql (in sorted order) on the DB server after 'drizzle-kit push'"
fi

log "Seeding database..."
sudo -u "${DEPLOY_USER}" docker compose -f "${COMPOSE_FILE}" exec -T app npx tsx scripts/seed.ts 2>&1 || warn "Seed may need manual review"

# Store which compose file to use for deploy.sh
echo "${COMPOSE_FILE}" > "${APP_DIR}/.compose-file"
chown "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}/.compose-file"

###############################################################################
# 9. Setup Nginx reverse proxy
###############################################################################
log "Configuring Nginx..."

cat > /etc/nginx/sites-available/agentforge << 'NGINXEOF'
server {
    listen 80;
    server_name _;   # REPLACE with: api.yourdomain.com

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support (live chat + web widget)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;

        # SSE streaming support
        proxy_buffering off;
        proxy_cache off;

        # Max body size (for knowledge base uploads)
        client_max_body_size 10m;
    }
}
NGINXEOF

# Enable site
ln -sf /etc/nginx/sites-available/agentforge /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

nginx -t && systemctl reload nginx

###############################################################################
# 10. Create update script
###############################################################################
DEPLOY_SCRIPT="/home/${DEPLOY_USER}/apps/agentforge/deploy.sh"
# deploy.sh is already in the repo from our next step, but ensure permissions
chmod +x "${DEPLOY_SCRIPT}" 2>/dev/null || true

###############################################################################
# Done
###############################################################################
echo ""
echo "================================================================"
log "AgentForge setup complete!"
echo "================================================================"
echo ""
echo "  Services: $(sudo -u ${DEPLOY_USER} docker compose -f ${APP_DIR}/docker-compose.prod.yml ps --format '{{.Name}}: {{.Status}}' 2>/dev/null | tr '\n' ', ')"
echo ""
echo "  Health check:  curl http://localhost:3000/health"
echo ""
echo "  NEXT STEPS:"
echo "  1. Edit ${ENV_FILE}"
echo "     - Add your ANTHROPIC_API_KEY"
echo "     - Add WhatsApp credentials (if ready)"
echo "  2. Point your domain's DNS A record to this server's IP"
echo "  3. Update Nginx: sudo nano /etc/nginx/sites-available/agentforge"
echo "     - Replace 'server_name _;' with 'server_name api.yourdomain.com;'"
echo "     - sudo nginx -t && sudo systemctl reload nginx"
echo "  4. Get SSL: sudo certbot --nginx -d api.yourdomain.com"
echo "  5. Restart after .env changes: cd ${APP_DIR} && ./deploy.sh"
echo ""
echo "  Logs:    cd ${APP_DIR} && docker compose -f docker-compose.prod.yml logs -f app"
echo "  Update:  cd ${APP_DIR} && ./deploy.sh"
echo ""
